import { useEffect, useMemo, useState } from "react";
import {
  ArrowRight, Check, ChevronDown, ChevronLeft, ChevronRight, Heart,
  Menu, Minus, Plus, Search, ShoppingBag, Sparkles, Star, Truck, X,
} from "lucide-react";

type Product = {
  id: string; name: string; descriptor: string; price: number; compare?: number;
  rating: number; reviews: number; image: string; category: string; pet: string;
};

const image = (name: string) => `/__mockup/images/${name}`;
const products: Product[] = [
  { id:"bed", name:"PAWLI Cloud Bed", descriptor:"A soft landing for slow mornings.", price:2499, compare:2999, rating:4.9, reviews:214, image:image("pawli-cloud-bed.jpg"), category:"Sleep", pet:"Dog" },
  { id:"harness", name:"Everyday Walk Harness", descriptor:"Light, secure, ready for the long way home.", price:1299, compare:1599, rating:4.8, reviews:186, image:image("pawli-walk.jpg"), category:"Walk", pet:"Dog" },
  { id:"bowl", name:"Slow Feeder Bowl", descriptor:"Mealtimes, made a little more mindful.", price:899, rating:4.7, reviews:92, image:image("pawli-cat.jpg"), category:"Feed", pet:"Dog" },
  { id:"toy", name:"Interactive Treat Toy", descriptor:"Good thinking deserves a good reward.", price:699, compare:799, rating:4.8, reviews:74, image:image("pawli-cloud-bed.jpg"), category:"Play", pet:"Cat" },
  { id:"brush", name:"Gentle Grooming Brush", descriptor:"A kinder way to keep coats happy.", price:599, rating:4.6, reviews:61, image:image("pawli-cat.jpg"), category:"Groom", pet:"Dog" },
  { id:"bottle", name:"Travel Water Bottle", descriptor:"Hydration for wherever the day takes you.", price:799, rating:4.8, reviews:108, image:image("pawli-walk.jpg"), category:"Travel", pet:"Dog" },
];
const money = (n: number) => `₹${n.toLocaleString("en-IN")}`;

function Stars({ rating }: { rating: number }) {
  return <span className="flex items-center gap-0.5 text-[#c66c4d]">{[0,1,2,3,4].map(i => <Star key={i} size={12} fill={i < Math.round(rating) ? "currentColor" : "none"} />)}</span>;
}

function ProductCard({ product, wished, onWish, onOpen, onAdd }: { product: Product; wished: boolean; onWish:()=>void; onOpen:()=>void; onAdd:()=>void }) {
  return <article className="group">
    <div className="relative aspect-[.92] overflow-hidden rounded-[22px] bg-[#e8dfd1]">
      <img src={product.image} alt={product.name} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" />
      {product.compare && <span className="absolute left-3 top-3 rounded-full bg-[#f3e8d8] px-3 py-1 text-[10px] font-bold uppercase tracking-[.14em] text-[#a45a40]">Popular</span>}
      <button onClick={onWish} aria-label="Toggle wishlist" className="absolute right-3 top-3 grid size-9 place-items-center rounded-full bg-[#f8f3ec]/90 text-[#302e29] transition hover:bg-white">{<Heart size={16} fill={wished ? "#c66c4d" : "none"} color={wished ? "#c66c4d" : "currentColor"} />}</button>
      <button onClick={onAdd} className="absolute inset-x-3 bottom-3 translate-y-14 rounded-full bg-[#292b27] py-3 text-xs font-bold uppercase tracking-[.12em] text-[#faf5ed] opacity-0 transition group-hover:translate-y-0 group-hover:opacity-100">Quick add</button>
    </div>
    <button onClick={onOpen} className="mt-4 block text-left"><h3 className="font-['DM_Sans'] text-[15px] font-semibold text-[#292b27]">{product.name}</h3><p className="mt-1 text-xs leading-5 text-[#7d796e]">{product.descriptor}</p></button>
    <div className="mt-3 flex items-center gap-2"><Stars rating={product.rating}/><span className="text-[11px] text-[#8c877b]">{product.rating} · {product.reviews} reviews</span></div>
    <div className="mt-2 flex gap-2 text-sm font-semibold text-[#292b27]"><span>{money(product.price)}</span>{product.compare && <del className="font-normal text-[#9b9588]">{money(product.compare)}</del>}</div>
  </article>;
}

export function Storefront() {
  const [cart, setCart] = useState<Record<string, number>>(() => {
    try { return JSON.parse(localStorage.getItem("pawli-cart") || "{}"); } catch { return {}; }
  });
  const [wishlist, setWishlist] = useState<string[]>(() => {
    try { return JSON.parse(localStorage.getItem("pawli-wishlist") || "[]"); } catch { return []; }
  });
  const [overlay, setOverlay] = useState<"cart"|"search"|"checkout"|"product"|null>(null);
  const [selected, setSelected] = useState<Product>(products[0]);
  const [query, setQuery] = useState("");
  const [quiz, setQuiz] = useState({ pet:"", need:"" });
  const [coupon, setCoupon] = useState("");
  const [confirmed, setConfirmed] = useState(false);
  const [subscribed, setSubscribed] = useState(false);
  const [toast, setToast] = useState("");
  useEffect(() => { localStorage.setItem("pawli-cart", JSON.stringify(cart)); }, [cart]);
  useEffect(() => { localStorage.setItem("pawli-wishlist", JSON.stringify(wishlist)); }, [wishlist]);
  useEffect(() => {
    if (!toast) return;
    const timer = window.setTimeout(() => setToast(""), 2400);
    return () => window.clearTimeout(timer);
  }, [toast]);
  const add = (p: Product) => {
    setCart(c => ({...c, [p.id]:(c[p.id]||0)+1}));
    setToast(`${p.name} added to your bag`);
  };
  const remove = (id:string) => setCart(c => { const n={...c}; delete n[id]; return n; });
  const change = (id:string, d:number) => setCart(c => ({...c, [id]:Math.max(1,(c[id]||1)+d)}));
  const items = products.filter(p => cart[p.id]);
  const count = Object.values(cart).reduce((a,b)=>a+b,0);
  const subtotal = items.reduce((a,p)=>a+p.price*(cart[p.id]||0),0);
  const discount = coupon.toUpperCase()==="PAWLI10" ? Math.round(subtotal*.1) : 0;
  const shipping = subtotal === 0 || subtotal >= 999 ? 0 : 99;
  const total = Math.max(0, subtotal + shipping - discount);
  const filtered = useMemo(() => products.filter(p => `${p.name} ${p.category} ${p.pet}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const openProduct = (p:Product) => { setSelected(p); setOverlay("product"); };
  const scrollTo = (id:string) => document.getElementById(id)?.scrollIntoView({behavior:"smooth"});
  const savedProducts = products.filter(p => wishlist.includes(p.id));

  return <div className="min-h-screen overflow-x-hidden bg-[#f8f3eb] text-[#292b27] font-['DM_Sans']">
    <div className="bg-[#2f473c] px-4 py-2 text-center text-[10px] font-bold uppercase tracking-[.18em] text-[#f8f3eb]">Free shipping across India on orders above ₹999 <span className="ml-2 text-[#d9b98d]">✦</span></div>
    <header className="sticky top-0 z-30 border-b border-[#d9d1c4]/70 bg-[#f8f3eb]/95 backdrop-blur">
      <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 md:px-10">
        <button className="mr-4 md:hidden" onClick={()=>scrollTo("categories")}><Menu size={21}/></button>
        <button onClick={()=>window.scrollTo({top:0,behavior:"smooth"})} className="font-['Playfair_Display'] text-3xl font-bold tracking-[-.08em]">PAWLI<span className="text-[#c66c4d]">.</span></button>
        <div className="hidden items-center gap-7 text-[11px] font-bold uppercase tracking-[.14em] md:flex"><button onClick={()=>scrollTo("shop")}>Shop</button><button onClick={()=>scrollTo("categories")}>Dogs</button><button onClick={()=>scrollTo("categories")}>Cats</button><button onClick={()=>scrollTo("story")}>Our story</button></div>
        <div className="flex items-center gap-1"><button onClick={()=>setOverlay("search")} className="grid size-10 place-items-center rounded-full hover:bg-[#eee6da]"><Search size={18}/></button><button onClick={()=>scrollTo("wishlist")} className="relative grid size-10 place-items-center rounded-full hover:bg-[#eee6da]"><Heart size={18}/>{wishlist.length>0&&<i className="absolute right-1 top-1 size-1.5 rounded-full bg-[#c66c4d]"/>}</button><button onClick={()=>setOverlay("cart")} className="relative grid size-10 place-items-center rounded-full bg-[#292b27] text-[#f8f3eb]"><ShoppingBag size={17}/>{count>0&&<span className="absolute -right-1 -top-1 grid size-5 place-items-center rounded-full bg-[#c66c4d] text-[10px]">{count}</span>}</button></div>
      </nav>
    </header>

    <main>
      <section className="mx-auto grid max-w-7xl gap-8 px-5 pb-16 pt-7 md:grid-cols-[.78fr_1.22fr] md:items-center md:px-10 md:pb-24 md:pt-12">
        <div className="order-2 md:order-1"><p className="mb-5 text-[11px] font-bold uppercase tracking-[.22em] text-[#c66c4d]">Modern pet care for the way you live</p><h1 className="max-w-xl font-['Playfair_Display'] text-[clamp(3.2rem,7vw,6.8rem)] leading-[.9] tracking-[-.07em]">Everything they need.<br/><em className="font-normal text-[#c66c4d]">Everything they love.</em></h1><p className="mt-7 max-w-sm text-base leading-7 text-[#716d63]">Thoughtfully designed essentials for happier pets and easier everyday life.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={()=>scrollTo("shop")} className="rounded-full bg-[#292b27] px-6 py-3.5 text-xs font-bold uppercase tracking-[.12em] text-[#f8f3eb] transition hover:bg-[#c66c4d]">Shop best sellers <ArrowRight className="ml-2 inline" size={14}/></button><button onClick={()=>scrollTo("categories")} className="rounded-full border border-[#bdb4a5] px-6 py-3.5 text-xs font-bold uppercase tracking-[.12em]">Shop for dogs</button></div><div className="mt-12 flex gap-8 border-t border-[#d9d1c4] pt-5 text-xs text-[#716d63]"><span><b className="block text-lg text-[#292b27]">Made in India</b>with everyday care</span><span><b className="block text-lg text-[#292b27]">4.8/5</b>pet parent rating</span></div></div>
        <div className="order-1 relative aspect-[.88] overflow-hidden rounded-[28px] md:order-2 md:aspect-[1.05]"><img src={image("pawli-hero.jpg")} alt="Golden retriever on a cloud bed" className="h-full w-full object-cover"/><div className="absolute bottom-5 left-5 rounded-2xl bg-[#f8f3eb]/90 px-4 py-3 backdrop-blur"><span className="text-[10px] uppercase tracking-[.16em] text-[#817b6e]">The soft landing</span><b className="mt-1 block font-['Playfair_Display'] text-xl">Cloud Bed</b></div></div>
      </section>

      <section id="categories" className="bg-[#e8e0d3] px-5 py-16 md:px-10 md:py-24"><div className="mx-auto max-w-7xl"><div className="mb-9 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#c66c4d]">Find their kind of happy</p><h2 className="mt-3 font-['Playfair_Display'] text-4xl tracking-[-.05em] md:text-6xl">Made for every kind<br className="hidden md:block"/> of companion.</h2></div><button onClick={()=>scrollTo("shop")} className="hidden text-xs font-bold uppercase tracking-[.14em] md:block">View all <ArrowRight className="ml-2 inline" size={14}/></button></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Dogs","Walks, playtime & everyday essentials.","pawli-walk.jpg"],["Cats","Comfort, enrichment & everyday care.","pawli-cat.jpg"],["Grooming","Keep them feeling their best.","pawli-cloud-bed.jpg"],["Travel","Adventure-ready essentials.","pawli-life.jpg"]].map(([t,d,img],i)=><button key={t} onClick={()=>scrollTo("shop")} className={`group relative aspect-[.82] overflow-hidden rounded-[20px] text-left ${i===1?"lg:translate-y-8":""}`}><img src={image(img)} alt={t} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-[#1e2821]/80 via-transparent to-transparent"/><div className="absolute inset-x-5 bottom-5 text-[#f8f3eb]"><h3 className="font-['Playfair_Display'] text-3xl">{t}</h3><p className="mt-1 text-xs text-[#eee3d3]">{d}</p></div></button>)}</div></div></section>

      <section id="shop" className="mx-auto max-w-7xl px-5 py-20 md:px-10 md:py-28"><div className="mb-10 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#c66c4d]">The everyday edit</p><h2 className="mt-3 font-['Playfair_Display'] text-5xl tracking-[-.06em]">Best sellers</h2></div><button onClick={()=>setOverlay("search")} className="hidden rounded-full border border-[#bdb4a5] px-5 py-3 text-[10px] font-bold uppercase tracking-[.15em] md:block">Browse everything</button></div><div className="grid grid-cols-2 gap-x-3 gap-y-10 md:grid-cols-3 md:gap-x-6 lg:grid-cols-4">{products.map(p=><ProductCard key={p.id} product={p} wished={wishlist.includes(p.id)} onWish={()=>setWishlist(w=>w.includes(p.id)?w.filter(x=>x!==p.id):[...w,p.id])} onOpen={()=>openProduct(p)} onAdd={()=>add(p)}/>)}</div></section>

      <section id="story" className="bg-[#2f473c] px-5 py-20 text-[#f8f3eb] md:px-10 md:py-28"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-[1fr_1.15fr] md:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#d9b98d]">Designed around real pet-parent life</p><h2 className="mt-5 max-w-lg font-['Playfair_Display'] text-5xl leading-[.95] tracking-[-.05em] md:text-7xl">Small details.<br/><em className="font-normal text-[#d9b98d]">Better days.</em></h2><p className="mt-7 max-w-md text-sm leading-7 text-[#c9c7bb]">We obsess over the tiny things that make routines lighter, from the way a bed holds its shape to a bottle that never leaks in your tote.</p></div><div className="grid gap-8 sm:grid-cols-3">{[["01","Comfort","Designed around how pets actually rest, play and move."],["02","Convenience","Simple essentials that make everyday routines easier."],["03","Quality","Thoughtfully selected materials and practical designs."]].map(([n,t,d])=><div key={t} className="border-t border-[#748477] pt-5"><span className="text-xs text-[#d9b98d]">{n}</span><h3 className="mt-7 font-['Playfair_Display'] text-3xl">{t}</h3><p className="mt-3 text-xs leading-6 text-[#c9c7bb]">{d}</p></div>)}</div></div></section>

      <section className="mx-auto grid max-w-7xl gap-10 px-5 py-20 md:grid-cols-[1.1fr_.9fr] md:items-center md:px-10 md:py-28"><div className="overflow-hidden rounded-[24px] bg-[#e6ddd0]"><img src={image("pawli-cloud-bed.jpg")} alt="PAWLI Cloud Bed" className="aspect-square w-full object-cover"/></div><div className="md:pl-8"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#c66c4d]">A PAWLI favourite</p><h2 className="mt-4 font-['Playfair_Display'] text-5xl leading-[.96] tracking-[-.06em]">Their favourite place might become yours too.</h2><div className="mt-5 flex items-center gap-2"><Stars rating={4.9}/><span className="text-xs text-[#817b6e]">4.9 · 214 reviews</span></div><p className="mt-5 text-2xl font-semibold">{money(2499)} <del className="ml-2 text-sm font-normal text-[#9b9588]">{money(2999)}</del></p><p className="mt-4 max-w-md text-sm leading-7 text-[#716d63]">A deep, supportive bed with a cloud-soft centre and washable cover. For dogs who deserve a little more room to dream.</p><div className="mt-7 flex gap-3"><button onClick={()=>{add(products[0]);setOverlay("cart")}} className="rounded-full bg-[#292b27] px-6 py-3.5 text-xs font-bold uppercase tracking-[.12em] text-[#f8f3eb]">Add to cart</button><button onClick={()=>openProduct(products[0])} className="rounded-full border border-[#bdb4a5] px-6 py-3.5 text-xs font-bold uppercase tracking-[.12em]">See details</button></div><div className="mt-8 border-t border-[#d9d1c4] pt-5 text-xs text-[#716d63]">Available in <b className="text-[#292b27]">Sage, Oat & Clay</b> · Small, Medium, Large</div></div></section>

      <section className="bg-[#d9b98d] px-5 py-16 md:px-10"><div className="mx-auto max-w-4xl text-center"><Sparkles className="mx-auto text-[#8e533d]" size={22}/><p className="mt-5 text-[10px] font-bold uppercase tracking-[.2em] text-[#8e533d]">A little help goes a long way</p><h2 className="mt-4 font-['Playfair_Display'] text-5xl tracking-[-.06em]">Help us find their perfect pick.</h2><div className="mx-auto mt-9 max-w-xl rounded-[22px] bg-[#f8f3eb] p-6 text-left shadow-[0_12px_35px_rgba(73,52,31,.1)]"><p className="text-sm font-semibold">{quiz.pet ? "What are you looking for?" : "What kind of companion are you shopping for?"}</p>{!quiz.pet?<div className="mt-5 grid grid-cols-2 gap-3"><button onClick={()=>setQuiz({...quiz,pet:"Dog"})} className="rounded-xl border border-[#c9bdac] p-4 text-left hover:border-[#c66c4d]"><b>Dogs</b><span className="mt-1 block text-xs text-[#817b6e]">Walk, play, rest</span></button><button onClick={()=>setQuiz({...quiz,pet:"Cat"})} className="rounded-xl border border-[#c9bdac] p-4 text-left hover:border-[#c66c4d]"><b>Cats</b><span className="mt-1 block text-xs text-[#817b6e]">Comfort, curiosity</span></button></div>:<><div className="mt-5 flex flex-wrap gap-2">{["Walk","Play","Sleep","Groom","Travel"].map(n=><button key={n} onClick={()=>setQuiz({...quiz,need:n})} className={`rounded-full border px-4 py-2 text-xs ${quiz.need===n?"border-[#c66c4d] bg-[#c66c4d] text-white":"border-[#c9bdac]"}`}>{n}</button>)}</div>{quiz.need&&<button onClick={()=>{const p=products.find(x=>x.category===quiz.need)||products[0];openProduct(p)}} className="mt-6 rounded-full bg-[#292b27] px-5 py-3 text-xs font-bold uppercase tracking-[.12em] text-white">Show my picks <ArrowRight className="ml-2 inline" size={14}/></button>}</>}</div></div></section>

      <section className="mx-auto max-w-7xl px-5 py-20 md:px-10 md:py-28"><div className="relative min-h-[420px] overflow-hidden rounded-[25px]"><img src={image("pawli-life.jpg")} alt="Life with PAWLI" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-[#202921]/75 via-[#202921]/20 to-transparent"/><div className="relative max-w-lg px-7 py-16 text-[#f8f3eb] md:px-16 md:py-24"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#d9b98d]">The PAWLI point of view</p><h2 className="mt-5 font-['Playfair_Display'] text-5xl leading-[.95] tracking-[-.05em]">Life is better with them in it.</h2><p className="mt-6 text-sm leading-7 text-[#e4ddd3]">From morning walks to lazy afternoons, PAWLI is designed for all the little moments you share.</p><button onClick={()=>scrollTo("shop")} className="mt-7 rounded-full bg-[#f8f3eb] px-6 py-3.5 text-xs font-bold uppercase tracking-[.12em] text-[#292b27]">Explore PAWLI <ArrowRight className="ml-2 inline" size={14}/></button></div></div></section>

      <section className="border-y border-[#ddd4c7] bg-[#f2eadf] px-5 py-10 md:px-10"><div className="mx-auto grid max-w-7xl gap-6 text-center sm:grid-cols-4">{[["Easy returns","30-day, no-fuss"],["Fast India-wide delivery","Packed with care"],["Secure checkout","Demo-safe payments"],["Pet-parent approved","Made for real life"]].map(([a,b])=><div key={a} className="flex items-center justify-center gap-3 text-left sm:block"><Check className="text-[#c66c4d] sm:mx-auto"/><div><b className="block text-sm">{a}</b><span className="text-xs text-[#817b6e]">{b}</span></div></div>)}</div></section>

       <section id="wishlist" className="mx-auto max-w-7xl px-5 py-20 md:px-10"><div className="flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#c66c4d]">Your saved edit</p><h2 className="mt-3 font-['Playfair_Display'] text-5xl tracking-[-.06em]">Things worth coming back to.</h2></div>{savedProducts.length > 0 && <span className="text-xs text-[#817b6e]">{savedProducts.length} saved {savedProducts.length === 1 ? "piece" : "pieces"}</span>}</div>{savedProducts.length > 0 ? <div className="mt-10 grid grid-cols-2 gap-x-3 gap-y-10 md:grid-cols-3 md:gap-x-6 lg:grid-cols-4">{savedProducts.map(p=><ProductCard key={p.id} product={p} wished onWish={()=>setWishlist(w=>w.filter(x=>x!==p.id))} onOpen={()=>openProduct(p)} onAdd={()=>add(p)}/>)}</div> : <div className="mt-10 flex flex-col items-center rounded-[22px] border border-dashed border-[#cfc5b7] bg-[#fbf7f0] px-6 py-14 text-center"><Heart className="text-[#c66c4d]" size={24}/><h3 className="mt-5 font-['Playfair_Display'] text-3xl">Nothing saved yet.</h3><p className="mt-2 max-w-sm text-sm leading-6 text-[#817b6e]">Tap the heart on anything that feels like them, and it will wait here for you.</p><button onClick={()=>scrollTo("shop")} className="mt-6 rounded-full bg-[#292b27] px-6 py-3 text-xs font-bold uppercase tracking-[.12em] text-white">Explore best sellers</button></div>}</section>
       <section id="reviews" className="bg-[#efe7dc] px-5 py-20 md:px-10"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#c66c4d]">From the PAWLI community</p><h2 className="mt-3 font-['Playfair_Display'] text-5xl tracking-[-.06em]">Good words, demo edition.</h2></div><span className="hidden text-xs text-[#817b6e] md:block">Illustrative reviews for this portfolio prototype</span></div><div className="mt-10 grid gap-4 md:grid-cols-3">{[["Ananya & Bruno","Interactive Treat Toy","Bruno usually destroys toys in days. This one has actually survived.","4.9"],["Rhea & Miso","PAWLI Cloud Bed","Miso has officially claimed the sunny corner. The bed is gorgeous too.","5.0"],["Kabir & Dobby","Everyday Walk Harness","Thoughtful fit, no fussy straps, and Dobby actually walks beside me now.","4.8"]].map(([n,p,t,r])=><div key={n} className="rounded-[20px] border border-[#ddd4c7] bg-[#fbf7f0] p-6"><Stars rating={5}/><p className="mt-5 font-['Playfair_Display'] text-2xl leading-tight">“{t}”</p><p className="mt-6 text-xs text-[#817b6e]"><b className="text-[#292b27]">{n}</b> · {p} · {r}/5</p><span className="mt-4 inline-block text-[9px] font-bold uppercase tracking-[.16em] text-[#a79e91]">Demo review · not a real testimonial</span></div>)}</div></div></section>

      <section className="bg-[#c66c4d] px-5 py-14 text-[#fff5ea] md:px-10"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 md:flex-row md:items-center"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-[#f4cdb5]">For birthdays, new pets & every excuse</p><h2 className="mt-3 font-['Playfair_Display'] text-5xl tracking-[-.05em]">Something they'll actually love.</h2></div><button onClick={()=>scrollTo("shop")} className="rounded-full bg-[#f8f3eb] px-6 py-3.5 text-xs font-bold uppercase tracking-[.12em] text-[#292b27]">Shop gifts <ArrowRight className="ml-2 inline" size={14}/></button></div></section>
    </main>

    <footer className="bg-[#292b27] px-5 py-14 text-[#f8f3eb] md:px-10 md:py-20"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-[1.4fr_1fr_1fr_1.4fr]"><div><div className="font-['Playfair_Display'] text-4xl tracking-[-.08em]">PAWLI<span className="text-[#c66c4d]">.</span></div><p className="mt-4 max-w-xs text-sm leading-6 text-[#aaa99d]">Better days for better companions.<br/>Thoughtfully designed in India.</p></div><div><h4 className="text-[10px] font-bold uppercase tracking-[.18em] text-[#d9b98d]">Shop</h4><div className="mt-5 grid gap-3 text-sm text-[#c8c6ba]"><button onClick={()=>scrollTo("categories")} className="text-left">Dogs</button><button onClick={()=>scrollTo("categories")} className="text-left">Cats</button><button onClick={()=>scrollTo("shop")} className="text-left">Grooming</button><button onClick={()=>scrollTo("shop")} className="text-left">Travel</button></div></div><div><h4 className="text-[10px] font-bold uppercase tracking-[.18em] text-[#d9b98d]">Customer care</h4><div className="mt-5 grid gap-3 text-sm text-[#c8c6ba]"><button onClick={()=>setOverlay("search")} className="text-left">Contact</button><button onClick={()=>scrollTo("reviews")} className="text-left">Shipping & returns</button><button onClick={()=>scrollTo("reviews")} className="text-left">FAQ</button><button onClick={()=>scrollTo("story")} className="text-left">Our story</button></div></div><div><h4 className="text-[10px] font-bold uppercase tracking-[.18em] text-[#d9b98d]">More good days together.</h4><p className="mt-4 text-sm leading-6 text-[#aaa99d]">Notes on living well with your favourite people.</p>{subscribed?<p className="mt-5 flex items-center gap-2 text-sm text-[#d9b98d]"><Check size={16}/> You're on the list.</p>:<div className="mt-5 flex border-b border-[#666960] pb-3"><input placeholder="Your email address" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-[#77796e]"/><button onClick={()=>{setSubscribed(true);setToast("You're on the PAWLI list")}} className="text-xs font-bold uppercase tracking-[.12em] text-[#d9b98d]">Subscribe</button></div>}</div></div><div className="mx-auto mt-14 max-w-7xl border-t border-[#4d514a] pt-6 text-[10px] uppercase tracking-[.13em] text-[#77796e]">© 2025 PAWLI · A Kaeon Studios portfolio prototype · Frontend demo only</div></footer>

    {toast && <div role="status" className="fixed bottom-5 left-1/2 z-[60] flex -translate-x-1/2 items-center gap-2 rounded-full bg-[#292b27] px-5 py-3 text-xs font-semibold text-[#f8f3eb] shadow-xl"><Check size={15} className="text-[#d9b98d]"/>{toast}</div>}

    {overlay&&<div className="fixed inset-0 z-50 bg-[#292b27]/50 backdrop-blur-sm" onClick={()=>setOverlay(null)}><div onClick={e=>e.stopPropagation()} className={`absolute right-0 top-0 h-full w-full overflow-y-auto bg-[#f8f3eb] p-5 shadow-2xl md:w-[470px] md:p-8 ${overlay==="search"?"md:w-[620px]":""}`}>
      <div className="flex items-center justify-between"><span className="font-['Playfair_Display'] text-3xl">{overlay==="cart"?"Your bag":overlay==="checkout"?"Checkout":overlay==="product"?selected.name:"Find your PAWLI"}</span><button onClick={()=>setOverlay(null)} className="grid size-10 place-items-center rounded-full bg-[#eee6da]"><X size={18}/></button></div>
       {overlay==="search"&&<><div className="mt-8 flex items-center gap-3 border-b border-[#bdb4a5] pb-3"><Search size={19}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products, categories, pets..." className="flex-1 bg-transparent text-base outline-none"/></div>{filtered.length > 0 ? <div className="mt-8 grid grid-cols-2 gap-5">{filtered.map(p=><ProductCard key={p.id} product={p} wished={wishlist.includes(p.id)} onWish={()=>setWishlist(w=>w.includes(p.id)?w.filter(x=>x!==p.id):[...w,p.id])} onOpen={()=>openProduct(p)} onAdd={()=>add(p)}/>)}</div> : <div className="py-20 text-center"><Search className="mx-auto text-[#c66c4d]" size={25}/><h3 className="mt-5 font-['Playfair_Display'] text-3xl">No perfect match yet.</h3><p className="mt-2 text-sm text-[#817b6e]">Try “walk”, “cat”, or “bed”.</p><button onClick={()=>setQuery("")} className="mt-6 rounded-full border border-[#bdb4a5] px-5 py-3 text-xs font-bold uppercase tracking-[.12em]">Show everything</button></div>}</>}
      {overlay==="cart"&&<Cart items={items} cart={cart} subtotal={subtotal} total={total} coupon={coupon} setCoupon={setCoupon} change={change} remove={remove} onCheckout={()=>setOverlay("checkout")} onShop={()=>setOverlay(null)}/>}
      {overlay==="product"&&<ProductDetail product={selected} wished={wishlist.includes(selected.id)} onWish={()=>setWishlist(w=>w.includes(selected.id)?w.filter(x=>x!==selected.id):[...w,selected.id])} onAdd={()=>{add(selected);setOverlay("cart")}}/>}
      {overlay==="checkout"&&<Checkout total={total} confirmed={confirmed} setConfirmed={setConfirmed} onDone={()=>{setCart({});setOverlay(null);setConfirmed(false)}}/>}
    </div></div>}
  </div>;
}

function Cart({items,cart,subtotal,total,coupon,setCoupon,change,remove,onCheckout,onShop}:{items:Product[];cart:Record<string,number>;subtotal:number;total:number;coupon:string;setCoupon:(s:string)=>void;change:(id:string,d:number)=>void;remove:(id:string)=>void;onCheckout:()=>void;onShop:()=>void}) {
  return <div className="mt-8">{!items.length?<div className="py-20 text-center"><ShoppingBag className="mx-auto text-[#c66c4d]" size={30}/><h3 className="mt-5 font-['Playfair_Display'] text-3xl">Your bag is waiting.</h3><p className="mt-2 text-sm text-[#817b6e]">A few good things for them, perhaps?</p><button onClick={onShop} className="mt-7 rounded-full bg-[#292b27] px-6 py-3 text-xs font-bold uppercase tracking-[.12em] text-white">Continue shopping</button></div>:<><div className="grid gap-5">{items.map(p=><div key={p.id} className="flex gap-4 border-b border-[#ddd4c7] pb-5"><img src={p.image} alt="" className="size-20 rounded-xl object-cover"/><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><b className="text-sm">{p.name}</b><button onClick={()=>remove(p.id)}><X size={15}/></button></div><span className="text-xs text-[#817b6e]">{money(p.price)}</span><div className="mt-3 flex items-center gap-3"><button onClick={()=>change(p.id,-1)} className="grid size-7 place-items-center rounded-full border"><Minus size={12}/></button><span className="text-xs">{cart[p.id]}</span><button onClick={()=>change(p.id,1)} className="grid size-7 place-items-center rounded-full border"><Plus size={12}/></button></div></div></div>)}</div><div className="mt-8 flex gap-2"><input value={coupon} onChange={e=>setCoupon(e.target.value)} placeholder="Coupon code" className="flex-1 rounded-full border border-[#cfc5b7] bg-transparent px-4 py-3 text-xs outline-none"/><button className="rounded-full border px-4 text-xs font-bold">Apply</button></div><div className="mt-8 space-y-3 border-t border-[#cfc5b7] pt-5 text-sm"><div className="flex justify-between"><span>Subtotal</span><b>{money(subtotal)}</b></div><div className="flex justify-between text-[#817b6e]"><span>Shipping</span><span>{subtotal>=999?"Free":money(99)}</span></div>{subtotal > 0 && subtotal < 999 && <p className="text-[11px] text-[#c66c4d]">Add {money(999-subtotal)} more for free shipping.</p>}{coupon.toUpperCase()==="PAWLI10"&&<div className="flex justify-between text-[#c66c4d]"><span>PAWLI10</span><span>-10%</span></div>}<div className="flex justify-between border-t border-[#cfc5b7] pt-4 text-lg"><b>Total</b><b>{money(total)}</b></div></div><button onClick={onCheckout} className="mt-7 w-full rounded-full bg-[#292b27] py-4 text-xs font-bold uppercase tracking-[.15em] text-white">Proceed to checkout <ArrowRight className="ml-2 inline" size={15}/></button></>}</div>;
}

function ProductDetail({product,wished,onWish,onAdd}:{product:Product;wished:boolean;onWish:()=>void;onAdd:()=>void}) {
  const [qty,setQty]=useState(1); const [size,setSize]=useState("M");
  return <div className="mt-7"><img src={product.image} alt={product.name} className="aspect-square w-full rounded-[20px] object-cover"/><div className="mt-6 flex items-center justify-between"><div><Stars rating={product.rating}/><span className="mt-1 block text-xs text-[#817b6e]">{product.rating} · {product.reviews} reviews</span></div><button onClick={onWish}><Heart fill={wished?"#c66c4d":"none"} color={wished?"#c66c4d":"currentColor"}/></button></div><p className="mt-5 text-2xl font-semibold">{money(product.price)} {product.compare&&<del className="ml-2 text-sm font-normal text-[#9b9588]">{money(product.compare)}</del>}</p><p className="mt-4 text-sm leading-7 text-[#716d63]">Thoughtfully made for everyday comfort, with details that hold up to real life and real love.</p><div className="mt-6"><span className="text-xs font-bold uppercase tracking-[.14em]">Size</span><div className="mt-3 flex gap-2">{["S","M","L"].map(x=><button key={x} onClick={()=>setSize(x)} className={`grid size-10 place-items-center rounded-full border text-xs ${size===x?"border-[#c66c4d] bg-[#c66c4d] text-white":""}`}>{x}</button>)}</div></div><div className="mt-6 flex gap-3"><div className="flex items-center rounded-full border border-[#cfc5b7]"><button onClick={()=>setQty(Math.max(1,qty-1))} className="p-3"><Minus size={14}/></button><span className="w-5 text-center text-xs">{qty}</span><button onClick={()=>setQty(qty+1)} className="p-3"><Plus size={14}/></button></div><button onClick={()=>{for(let i=0;i<qty;i++)onAdd()}} className="flex-1 rounded-full bg-[#292b27] py-3 text-xs font-bold uppercase tracking-[.12em] text-white">Add to cart</button></div><div className="mt-7 border-y border-[#ddd4c7] text-sm">{["Product details","Materials","Sizing guide","Care instructions","Shipping & returns"].map(x=><details key={x} className="border-b border-[#ddd4c7] py-4 last:border-0"><summary className="flex cursor-pointer list-none justify-between font-semibold">{x}<ChevronDown size={16}/></summary><p className="mt-3 text-xs leading-6 text-[#817b6e]">Made for modern homes and the everyday rituals you share. Simple, considered, dependable.</p></details>)}</div></div>;
}

function Checkout({total,confirmed,setConfirmed,onDone}:{total:number;confirmed:boolean;setConfirmed:(v:boolean)=>void;onDone:()=>void}) {
  const [method,setMethod]=useState("UPI");
  if(confirmed)return <div className="py-16 text-center"><div className="mx-auto grid size-16 place-items-center rounded-full bg-[#dce6d8] text-[#2f473c]"><Check size={28}/></div><h2 className="mt-7 font-['Playfair_Display'] text-4xl">Order confirmed.</h2><p className="mt-3 text-sm leading-6 text-[#817b6e]">Your PAWLI order is on its way.<br/>Order <b className="text-[#292b27]">#PWL-4821</b> · arriving 18–20 June</p><p className="mt-7 text-xl font-semibold">{money(total)}</p><button onClick={onDone} className="mt-8 rounded-full bg-[#292b27] px-7 py-3 text-xs font-bold uppercase tracking-[.14em] text-white">Continue shopping</button></div>;
  return <div className="mt-7"><div className="space-y-3"><label className="block text-xs font-bold uppercase tracking-[.12em]">Contact<input placeholder="Email address" className="mt-2 w-full rounded-xl border border-[#cfc5b7] bg-transparent p-3 text-sm outline-none"/></label><label className="block text-xs font-bold uppercase tracking-[.12em]">Delivery address<input placeholder="Full name · address · city · PIN" className="mt-2 w-full rounded-xl border border-[#cfc5b7] bg-transparent p-3 text-sm outline-none"/></label></div><div className="mt-8"><span className="text-xs font-bold uppercase tracking-[.12em]">Payment method</span><div className="mt-3 grid grid-cols-2 gap-2">{["UPI","Card","Net banking","Wallet"].map(x=><button key={x} onClick={()=>setMethod(x)} className={`rounded-xl border p-3 text-left text-xs ${method===x?"border-[#c66c4d] bg-[#f1dfd0]":""}`}>{x}</button>)}</div><div className="mt-4 rounded-xl bg-[#eee6da] p-4 text-xs text-[#817b6e]">{method==="UPI"?"Enter a UPI ID on the next step.":`${method} details would appear here in a real checkout.`}</div></div><div className="mt-8 border-t border-[#cfc5b7] pt-5"><div className="flex justify-between text-lg"><b>Pay today</b><b>{money(total)}</b></div><button onClick={()=>setConfirmed(true)} className="mt-6 w-full rounded-full bg-[#292b27] py-4 text-xs font-bold uppercase tracking-[.15em] text-white">Pay {money(total)} <ArrowRight className="ml-2 inline" size={15}/></button><p className="mt-4 text-center text-[10px] text-[#9b9588]">Demo payment only · no real card data is collected</p></div></div>;
}

export default Storefront;